server:
  port: 9000
spring:
  application:
    name: util
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/util?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0 # 操作的是0号数据库
    password: 
  cache:
    redis:
      time-to-live: 1800000 # 过期时间
    type: redis
  # 邮箱
  mail:
    host: 
    username: 
    password: 
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net:ssl.SSLSocketFactory
        debug: true


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: del_flag
      logic-delete-value: 2
      logic-not-delete-value: 0


